server {
    listen 80 default_server;
    server_name aptdesign.cn www.aptdesign.cn 124.221.130.35 _;

    root /var/www/aptdesign;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|gif|webp|svg|ico)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        try_files $uri =404;
    }
}
